.\" Process this file with
.\" groff -man -Tascii clone-all.1
.\"
.TH "CLONE-ALL" 1 "APRIL 2014" Unix "User Manuals"
.SH "NAME"
\fBclone-all\fR \- Clones all public repos or gists from Github
.SH SYNOPSIS
\fBclone-all\fR  \-\-version
.br
\fBclone-all\fR  [options] username [\fI<path>\fR]
.SH DESCRIPTION
Clones all public repos or gists from Github based on a username to a specified path.  If no path is specified, then defaults to directories named after feed value in \fB$HOME/Downloads\fR.
.SH OPTIONS
.IP "\fB[-f, --feed] \fIvalue\fR"
The type of feed to grab from; \fIvalue\fR can either be \fBrepos\fR or \fBgists\fR.  The default is \fBrepos\fR.
.SH RETURN VALUES
The following exit codes are possible:
.IP "\fb0\fR"
success
.IP "\fb1\fR"
general error, typically a bad flag or value
.IP "\fb2\fR"
missing dependency error
.IP "\fb3\fR"
invalid or missing user
.SH REPORTING BUGS
.RI "Report bugs to the Github repository <" "https://github.com/iamnewton/clone-all/issues" ">"
.SH AUTHOR
.RI "Newton
